# Generated by Django 4.1.1 on 2022-09-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="brand",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("quantity", models.IntegerField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Active"), ("B", "Inactive")],
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("b", "Blue"),
                            ("bl", "Black"),
                            ("r", "Red"),
                            ("w", "White"),
                            ("g", "Green"),
                            ("y", "Yellow"),
                            ("p", "purple"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Men"), ("w", "Women"), ("c", "Child")],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="stores",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("owner", models.CharField(blank=True, max_length=200, null=True)),
                ("outlets", models.IntegerField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Active"), ("B", "Inactive")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="src.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="store_owner",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("owner_name", models.CharField(blank=True, max_length=200, null=True)),
                ("store_count", models.IntegerField(blank=True)),
                (
                    "owner_status",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Active"), ("B", "Inactive")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "store_name",
                    models.ManyToManyField(related_name="store_name", to="src.stores"),
                ),
            ],
        ),
    ]
