# Generated by Django 4.1.1 on 2022-09-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
