# Generated by Django 4.1.1 on 2022-09-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="sales",
            fields=[
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="src.stores",
                    ),
                ),
            ],
        ),
    ]
