# Generated by Django 4.1.1 on 2022-09-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="depart_store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Departed_Store",
                to="src.stores",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Child", "Child"),
                    ("Unisex", "Unisex"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Blue", "Blue"),
                    ("Black", "Black"),
                    ("Red", "Red"),
                    ("White", "White"),
                    ("Green", "Green"),
                    ("Yellow", "Yellow"),
                    ("Purple", "purple"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="destination_store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Destination_Store",
                to="src.stores",
            ),
        ),
    ]
