# Generated by Django 4.1.1 on 2022-10-08 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_sales_depart_store_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_owner',
            name='store_name',
        ),
        migrations.AddField(
            model_name='sales',
            name='date_of_dispatch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.store_owner'),
        ),
    ]
