# Generated by Django 4.1.1 on 2022-10-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_remove_store_owner_store_name_sales_date_of_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity_shipment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
