# Generated by Django 4.1.1 on 2022-10-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_sales_quantity_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
