# Generated by Django 4.1.1 on 2022-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_owner',
            name='store_count',
        ),
        migrations.AddField(
            model_name='store_owner',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
