# Generated by Django 4.1.1 on 2022-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_remove_store_owner_store_count_store_owner_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='outlets',
        ),
        migrations.AddField(
            model_name='store_owner',
            name='store_count',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
