# Generated by Django 4.1.1 on 2022-10-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_remove_stores_outlets_store_owner_store_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='brand',
            new_name='brands',
        ),
    ]
