# Generated by Django 4.1.1 on 2022-10-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_rename_brand_stores_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='brands',
        ),
        migrations.AddField(
            model_name='brand',
            name='corresponding_stores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.stores'),
        ),
    ]
